name: CI-CD for .NET App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build -c Release --no-restore

    - name: Run Unit Tests
      run: dotnet test --no-build

    - name: Publish Application
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to IIS
      shell: cmd
      run: |
        xcopy /Y /E /I ./publish "C:\inetpub\wwwroot\MyDotNetApp"
